/// Flutter icons OrdersApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OrdersApp
///      fonts:
///       - asset: fonts/OrdersApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OrdersApp {
  OrdersApp._();

  static const _kFontFam = 'OrdersApp';
  static const String? _kFontPkg = null;

  static const IconData apple = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paypal = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
